name: Publish to pub.dev

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+*"

jobs:
  run-tests:
    uses: ./.github/workflows/ci.yml
  publish:
    permissions:
      id-token: write
    needs: run-tests
    uses: dart-lang/setup-dart/.github/workflows/publish.yml@v1
